backend:
  name: git-gateway
  branch: main # Branch to update
media_folder: static/images # Folder for media uploads
public_folder: /images # URL path for media
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts"
    folder: "content/blog" # Folder for blog content
    create: true # Allows users to create new documents
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}